### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by Nobody2414** [rxphyy/soundcloud-dark#1]
them comments are dark i cant see them also the queue button is practically invisible

**Comment by rxphyy** [comment]
Hi, thank you for bringing this to my attention. I have fixed the styles for the comments section aswell as for the 'Add to queue' section. If you find anything else, let me know!

**Comment by Nobody2414** [comment]
i found that the next up box once you click the queue button is very white

**Comment by rxphyy** [comment]
That should have been fixed with the previously mentionned update, are you still having issues?

**Comment by Nobody2414** [comment]
yes. 
![Screenshot 2024-04-03 8 30 22 AM](https://github.com/rxphyy/soundcloud-dark/assets/124017628/c6005ba0-6cae-41ec-aa0b-a8f6a036ed18)
